# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  tags:
      - '*'


env:
  DSS_VERSION: 11.4.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build with Ant
      run: |
        wget -q https://downloads.dataiku.com/public/studio/$DSS_VERSION/dataiku-dss-$DSS_VERSION.tar.gz
        tar -zxf dataiku-dss-$DSS_VERSION.tar.gz  dataiku-dss-$DSS_VERSION/dist
        tar -zxf dataiku-dss-$DSS_VERSION.tar.gz  dataiku-dss-$DSS_VERSION/lib
        export DKUINSTALLDIR=$(pwd)/dataiku-dss-$DSS_VERSION
        ant -noinput -buildfile build.xml
        rm -Rf dataiku-dss* java-build/
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dss-plugin-elasticsearch-index-template
        path: ./
    
    - name: Package plugin before release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        zip -r dss-plugin-elasticsearch-index-template-$GITHUB_REF_NAME.zip ./ -x "*/.*" -x ".*"
    
    - name: Create release and publish package
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dss-plugin-elasticsearch-index-template-$GITHUB_REF_NAME.zip
